# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Brian Hanifin
tagline: >-
  Stay-at-home dad, Tinkerer,
  Home Assistant enthusiast
description: DIY Home Automation with Home Assistant.
url: 'https://brianhanifin.com'
author: Brian Hanifin
avatar: /assets/img/brian-emoji.png
github:
  username: brianhanifin
twitter:
  username: brianhanifin
homeassistant:
  username: brianhanifin

social:
  name: Brian Hanifin
  email: blog@brianhanifin.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/brianhanifin
    - https://twitter.com/brianhanifin
    - https://community.home-assistant.io/u/brianhanifin

#google_site_verification: dCI8UCO8hrtyfnKPb5452HpLmoNA4ITtwGsjkysztX0

# My plugins
#--------------------------

# https://github.com/yihangho/emoji-for-jekyll
emoji-blacklist:

# https://github.com/riboseinc/jekyll-external-links/
external_links:
  selector: '#main a'
  #marker_html: "<span class='ico-ext'><i class='fas fa-external-link-square-alt'></i></span>"

# https://github.com/jekyll/jekyll-mentions
jekyll-mentions:
  base_url: https://community.home-assistant.io/u/
#--------------------------

# if your site type is Project Pages site, change below value to '/projectname'
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/Los_Angeles

google_analytics:
  # Fill with your Google Analytics ID
  id: 'UA-81748-9'
  # The Google Analytics pageviews switch.
  # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
  pv: false
  # superProxy baseURL and URL, only valid when `google_analytics.pv` is set to 'true'
  proxy_baseurl: ''
  proxy_url: ''


disqus:
  comments: true
  shortname: 'brianhanifin'

# The year your website first ran.
first_run: 2019

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    default_lang: yaml
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

jekyll_github_sample:

permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Home
          url: /
  -
    scope:
      path: assets/data
    values:
      layout: compress


sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor        # Avoid Jekyll mistakenly read the vender directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
